# Generated by Django 5.0.4 on 2024-05-23 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('UserName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=100)),
                ('Quyen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('MaHD', models.AutoField(primary_key=True, serialize=False)),
                ('NgayLap', models.DateField()),
                ('TongTien', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietHD',
            fields=[
                ('MaCTHD', models.AutoField(primary_key=True, serialize=False)),
                ('SoLuong', models.IntegerField()),
                ('ThanhTien', models.IntegerField()),
                ('MaSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SanPham_ChiTietHD', to='products.sanpham')),
                ('MaHD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HoaDon_ChiTietHD', to='account.hoadon')),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('MaKH', models.AutoField(primary_key=True, serialize=False)),
                ('TenKH', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100, unique=True)),
                ('SoDT', models.CharField(max_length=100)),
                ('DiaChi', models.CharField(max_length=100)),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Account_KhachHang', to='account.account')),
            ],
        ),
        migrations.AddField(
            model_name='hoadon',
            name='MaKH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KhachHang_HoaDon', to='account.khachhang'),
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('MaNV', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('TenNV', models.CharField(max_length=100)),
                ('GioiTinh', models.CharField(max_length=100)),
                ('NgaySinh', models.DateField()),
                ('Email', models.CharField(max_length=100, unique=True)),
                ('SoDT', models.CharField(max_length=100)),
                ('DiaChi', models.CharField(max_length=100)),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Account_NhanVien', to='account.account')),
            ],
        ),
        migrations.CreateModel(
            name='YeuThich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SanPham_YeuThich', to='products.sanpham')),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KhachHang_YeuThich', to='account.khachhang')),
            ],
        ),
    ]
