# Generated by Django 4.2.11 on 2024-05-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenNCC', models.CharField(max_length=200)),
                ('DiaChi', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('SDT', models.CharField(max_length=20)),
                ('WebSite', models.CharField(max_length=200)),
            ],
        ),
    ]
