# Generated by Django 5.0.4 on 2024-05-23 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('dashboard', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietPhieuNhap',
            fields=[
                ('MaCTPN', models.AutoField(primary_key=True, serialize=False)),
                ('SoLuong', models.IntegerField()),
                ('GiaNhap', models.IntegerField()),
                ('MaNCC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.nhacungcap')),
                ('MaSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuNhap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NgayNhap', models.DateField()),
                ('TrangThai', models.CharField(max_length=100)),
                ('TongTien', models.IntegerField()),
                ('MaNV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.nhanvien')),
            ],
        ),
        migrations.DeleteModel(
            name='NCC',
        ),
        migrations.AddField(
            model_name='chitietphieunhap',
            name='MaPhieuNhap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.phieunhap'),
        ),
    ]
