# Generated by Django 5.0.4 on 2024-05-23 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SanPham_Cart', to='products.sanpham')),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KhachHang_Cart', to='account.khachhang')),
            ],
        ),
    ]
