# Generated by Django 5.0.4 on 2024-05-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='SoLuong',
            field=models.IntegerField(default=1),
        ),
    ]
