# Generated by Django 5.0.4 on 2024-05-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_soluong'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ThanhTien',
            field=models.IntegerField(default=0),
        ),
    ]
