# Generated by Django 5.0.4 on 2024-05-23 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenLoai', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenNCC', models.CharField(max_length=200)),
                ('DiaChi', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('SDT', models.CharField(max_length=20)),
                ('WebSite', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenSP', models.CharField(max_length=255)),
                ('Soluong', models.IntegerField()),
                ('GiaNhap', models.IntegerField()),
                ('GiaBan', models.IntegerField()),
                ('Mota', models.TextField()),
                ('TrangThai', models.BooleanField(default=True)),
                ('Anh', models.ImageField(blank=True, default=None, null=True, upload_to='img')),
                ('TenThietBi', models.CharField(max_length=255)),
                ('MaLoai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.loaisp')),
                ('MaNCC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.nhacungcap')),
            ],
        ),
    ]
